# temporary solution, while k8s is not configured
services:
  postgres:
    container_name: postgres_container_emt
    hostname: postgres_container_emt
    image: postgres:latest
    restart: always
    ports:
      - '5435:5435'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data
    volumes:
      - db-postgres:/data

volumes:
  db-postgres: { }