# temporary solution, while k8s is not configured
version: '3.8'
services:
  postgres:
    container_name: postgres_container_emt
    hostname: postgres_container_emt
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-postgres:/var/lib/postgresql/data

volumes:
  db-postgres: { }