dbHost: localhost
dbPort: 5432
dbName: elt_database
dbUsername: elt_user
dbPassword: elt_pass
dbApplicationName: ${spring.application.name}
dbSchema: app_elo_match_tracker

spring:
  application:
    name: elo_match_tracker
    version: 0.0.1.test
    description: Manage player registrations and track 1v1 matches using the Elo ranking system.
  datasource:
    url: jdbc:postgresql://${dbHost}:${dbPort}/${dbName}?ApplicationName=${dbApplicationName}&currentSchema=${dbSchema}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2 # default is 10, set to a reasonable value
      schema: ${dbSchema}
  flyway:
    schemas: ${dbSchema}
  jpa:
    properties:
      hibernate:
        default_schema: ${dbSchema}
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
  info:
    env:
      enabled: true
  server:
    port: 9090

info:
  app:
    name: ${spring.application.name}
    version: ${spring.application.version}
    description: ${spring.application.description}

springdoc:
  swagger-ui:
    path: /
