dbHost: localhost
dbPort: 5432
dbName: template_name
dbUsername: template_username
dbPassword: template_password
dbSchema: app_java_spring_template

spring:
  application:
    name: java-spring-template
    version: 0.0.1.test
    description: java template project, feel free to change
  datasource:
    url: jdbc:postgresql://${dbHost}:${dbPort}/${dbName}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: ${dbSchema}
  jpa:
    properties:
      hibernate:
        default_schema: ${dbSchema}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
  info:
    env:
      enabled: true
  server:
    port: 9090

info:
  app:
    name: ${spring.application.name}
    version: ${spring.application.version}
    description: ${spring.application.description}

springdoc:
  swagger-ui:
    path: /
